site_name: Wagtail Transfer Documentation
theme:
  name: 'material'
  logo:
    icon: 'import_export'
  palette:
    primary: 'teal'
    accent: 'indigo'
markdown_extensions:
  - codehilite
nav:
  - Home: index.md
  - Basic Usage: basic_usage.md
